name: mlpc-2024
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - numpy=1.26.4
  - python=3.12
  - matplotlib=3.8.3
  - scikit-learn=1.4.2
  - scikit-optimize=0.10.1
  - torchmetrics=1.4.0
  - mlxtend=0.23.1 
  
